---
- hosts: web
  tasks: 
   - name: create a user
     user:
       name: synechron
       state: present
   - name: create a group
     group:
       name: synechron2
       state: present 
       
