---
- hosts: web
  tasks:
   - name: create a user
     user:
       name: devops
       state: present
   - name: install apache
     package:
       name: apache2
       state: present
   - name: service check for apache2
     service:
       name: apache2
       state: started
   - name: creating directory
     file:
       name: /var/www/html/webapp
       mode: 0777
       state: directory
   - name: creating FILE
     file:
       name: /var/www/html/webapp/ïndex.html
       state: touch
